# Generated by Django 5.2.6 on 2025-09-20 13:27

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('url', models.URLField(unique=True, verbose_name='URL статьи')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384, verbose_name='Векторное представление')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключевое слово')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('weight', models.FloatField(verbose_name='Вес ключевого слова')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_keywords', to='help.article', verbose_name='Статья')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_keywords', to='help.keyword', verbose_name='Ключевое слово')),
            ],
        ),
    ]
