# Generated by Django 5.2.6 on 2025-09-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ArticleKeyword',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
