# Generated by Django 5.2.6 on 2025-09-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracthistory',
            name='contract_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contracthistory',
            name='customer_inn',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contracthistory',
            name='vendor_inn',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='quotesessionhistory',
            name='customer_inn',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='quotesessionhistory',
            name='quote_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='quotesessionhistory',
            name='vendor_inn',
            field=models.PositiveBigIntegerField(),
        ),
    ]
