# Generated by Django 5.2.6 on 2025-09-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=2048)),
                ('contract_id', models.PositiveIntegerField()),
                ('contract_price', models.FloatField()),
                ('created_at', models.DateField()),
                ('category_name', models.CharField(max_length=1024)),
                ('customer_name', models.CharField(max_length=1024)),
                ('customer_inn', models.PositiveIntegerField()),
                ('vendor_name', models.CharField(max_length=1024)),
                ('vendor_inn', models.PositiveIntegerField()),
                ('fundamental_law', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteSessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_name', models.CharField(max_length=2048)),
                ('quote_id', models.PositiveIntegerField()),
                ('quote_price', models.FloatField()),
                ('quote_created_at', models.DateField()),
                ('quote_ended_at', models.DateField()),
                ('category_name', models.CharField(max_length=1024)),
                ('customer_name', models.CharField(max_length=1024)),
                ('customer_inn', models.PositiveIntegerField()),
                ('vendor_name', models.CharField(max_length=1024)),
                ('vendor_inn', models.PositiveIntegerField()),
                ('fundamental_law', models.CharField(max_length=64)),
            ],
        ),
    ]
