# Generated by Django 5.2.6 on 2025-09-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_date', models.DateField(null=True)),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки пользователя')),
            ],
        ),
    ]
