# Generated by Django 5.2.6 on 2025-09-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='action_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Тип действия'),
        ),
    ]
