# Generated by Django 5.2.6 on 2025-09-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_alter_querylog_action_type_alter_querylog_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='action_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Тип действия'),
        ),
    ]
