# Generated by Django 5.2.6 on 2025-09-20 13:27

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('normalized_text', models.TextField()),
                ('intent', models.CharField(help_text='Распознанное намерение пользователя', max_length=100, verbose_name='Интент')),
                ('action_type', models.CharField(max_length=20, verbose_name='Тип действия')),
                ('entities', models.JSONField(default=dict, verbose_name='Сущности')),
                ('confidence', models.FloatField(default=0.0, help_text='Уверенность модели в распознавании', validators=[django.core.validators.MinValueValidator(0.0, 'Уверенность не может быть отрицательной'), django.core.validators.MaxValueValidator(1.0, 'Уверенность не может превышать 1.0')], verbose_name='Уверенность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
