# Generated by Django 5.2.6 on 2025-09-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_alter_querylog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='action_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='entities',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сущности'),
        ),
    ]
