# Generated by Django 5.2.6 on 2025-09-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_alter_querylog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='rate',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
